### ISSUE TITLE
Cannot install gem

### ISSUE THREAD

**Issue by Overload119** [filewatcher/filewatcher-cli#19]
```
gem install filewatcher-cli
ERROR:  Could not find a valid gem 'filewatcher-cli' (>= 0) in any repository
```

```
gem install filewatcher-cli -s https://github.com/filewatcher/filewatcher-cli
ERROR:  Could not find a valid gem 'filewatcher-cli' (>= 0), here is why:
          Unable to download data from https://github.com/filewatcher/filewatcher-cli/ - bad response Not Found 404 (https://github.com/filewatcher/filewatcher-cli/specs.4.8.gz)
```

Can anyone shed some light on this?

**Comment by AlexWayfer** [comment]
Look at https://rubygems.org/gems/filewatcher-cli

![image](https://user-images.githubusercontent.com/6510020/107589041-27ef3300-6c16-11eb-9454-c913814ae97f.png)

The latest (and a single) version is `.beta`, but it's not stable and not included by default, so you have to specify this like `'>= 1.0.0.beta1', '< 2'`.

**Comment by kwight** [comment]
`gem install filewatcher-cli --prerelease` will also successfully install it.

**Comment by AlexWayfer** [comment]
The whole ecosystem has been released. :tada:
