### ISSUE TITLE
Multiple watch specifications no longer work

### ISSUE THREAD

**Issue by DannyBen** [filewatcher/filewatcher-cli#81]
In the old filewatcher CLI, these commands worked:

```bash
$ filewatcher "file1 file2" "echo hello"
$ filewatcher "dir1 file1" "echo hello"
```

and according to the documentation, this is the syntax for the new filewatcher - however, it does not work for me.

When using only one file or directory, it works.

```
$ filewatcher --version
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
Filewatcher 2.0.0
Filewatcher CLI 1.0.0
```

**Comment by AlexWayfer** [comment]
@DannyBen hello!

I'm not sure what do you mean, but I can provide you a new explicit information:
1. There is [`--daemon` option](https://github.com/filewatcher/filewatcher-cli#daemonizing-filewatcher-process) for putting a Filewatcher into background. I'm not sure, if this was enabled by default, very doubtful, but I recommend to use it explicitly anyway.
2. There is a new [`filewatcher-matrix` plugin](https://github.com/filewatcher/filewatcher-matrix) which can be very useful and comfortable for parallel processes. It works with CLI.

Let me know please do I understand you right and is it helpful.

**Comment by DannyBen** [comment]
No - I am not talking about any of these features.

I am talking about specifying more than one path to watch - this feature no longer works.

For example, if I want to watch two directories "one" and "two" - the old filewatcher worked, the new one does not.

This command does not execute on any change:

```
$ filewatcher "one two" "echo works"
```

**Comment by AlexWayfer** [comment]
@DannyBen thank you! I see the problem now. Technical details from the investigation:
1. There was `split_files_void_escaped_whitespace` in v1 for both `files` and `exclude`.
2. There is still `split_files_void_escaped_whitespace`, but only for `exclude`.

Conclusion: I should apply this method to the `files` argument.

I'm working on this, thank you.

**Comment by AlexWayfer** [comment]
According to TDD, I want to cover this functionality by tests, and from the Filewatcher core there is support of `Array` files, for example, but it's uncovered, and tests scripts are pretty strict… so it can consume more time than I'd like to, sorry.

**Comment by DannyBen** [comment]
No setup assistance needed. I just need to remember where I had this problem.
I will check right away.

**Comment by AlexWayfer** [comment]
> Confirmed. The `return_multiple_paths_support` branch works as expected.

Thank you, version `2.1` is coming.

**Comment by AlexWayfer** [comment]
I was wrong: Filewatcher 2.1, but CLI plugin is 1.1 now. Published.

Thank you for the report again.
